helpMessage = "List of commands: help, bus stations, train stations, route info, outages, look up breeze card. For other issues please contact (404)848-5000"
fallthroughMessage = "I didn't quite get that. Try another command or type helpme for a list of commands!"
breezecardMessage = "Enter a valid breezecard serial #"
notImplemented = "Not implemented yet!"
sampleAddress = "930 Spring Street NW, Atlanta, GA"